### ISSUE TITLE
Arch-Improvement

### ISSUE THREAD

**Issue by genaray** [pedryx/world-simulator#1]
https://github.com/pedryx/world-simulator/blob/59c6494c3aaaeb0d1186caea84e87baf6fbda72b/WorldSimulator/ECS/Arch/ArchSystem.cs#L29

Not sure if i am even allowed to help or suggest improvements. If not, ignore this issue here. 

Just looked at some code and saw that the arch systems can be improved. `world.Query` is quite slow and arch offers a bunch of other query apis for high-performance: https://github.com/genaray/Arch/wiki/Query-techniques

So those could he improved by a lot :) just my two cents. Otherwhise interesting project and good luck with your thesis!

**Comment by pedryx** [comment]
Thanks for the tip! I had plans to explore different query options in ECS libraries in the future, so I'll likely use a faster version that supports inlining.
